---
development:
  cloud_name: <%= ENV.fetch('CLOUDINARY_CLOUD_NAME') %>
  api_key: '<%= ENV.fetch('CLOUDINARY_API_KEY') %>'
  api_secret: <%= ENV.fetch('CLOUDINARY_API_SECRET') %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: <%= ENV.fetch('CLOUDINARY_CLOUD_NAME') %>
  api_key: '<%= ENV.fetch('CLOUDINARY_API_KEY') %>'
  api_secret: <%= ENV.fetch('CLOUDINARY_API_SECRET') %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: wantoro
  api_key: '854537683382731'
  api_secret: s8MHc1XNkEJ1fXrUuSKSf8imm2k
  enhance_image_tag: true
  static_image_support: false
